# Generated by Django 2.0.7 on 2018-08-07 05:44

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acrisure', '0002_auto_20180806_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='ded',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0.0'), default_currency='USD', max_digits=7),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='ded_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican peso'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ded_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican peso'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican peso'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
