# Generated by Django 2.0.7 on 2018-08-08 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acrisure', '0003_auto_20180807_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acrisure.Account'),
        ),
    ]
