# Generated by Django 2.0.7 on 2018-08-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acrisure', '0004_auto_20180808_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrisure.Company'),
        ),
    ]
