# Generated by Django 2.0.7 on 2018-08-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acrisure', '0005_auto_20180808_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acrisure.Policy'),
            preserve_default=False,
        ),
    ]
