# Generated by Django 2.0.7 on 2018-08-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acrisure', '0006_auto_20180808_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='acrisure.Policy'),
        ),
    ]
